INSERT INTO countries (country) values ('Afghanistan');
INSERT INTO countries (country) values ('Albania');
INSERT INTO countries (country) values ('Algeria');
INSERT INTO countries (country) values ('American Samoa');
INSERT INTO countries (country) values ('Andorra');
INSERT INTO countries (country) values ('Angola');
INSERT INTO countries (country) values ('Anguilla');
INSERT INTO countries (country) values ('Antarctica');
INSERT INTO countries (country) values ('Antigua');
INSERT INTO countries (country) values ('Argentina');
INSERT INTO countries (country) values ('Armenia');
INSERT INTO countries (country) values ('Aruba');
INSERT INTO countries (country) values ('Australia');
INSERT INTO countries (country) values ('Austria');
INSERT INTO countries (country) values ('Azerbaijan');
INSERT INTO countries (country) values ('Bahamas');
INSERT INTO countries (country) values ('Bahrain');
INSERT INTO countries (country) values ('Bangladesh');
INSERT INTO countries (country) values ('Barbados');
INSERT INTO countries (country) values ('Belarus');
INSERT INTO countries (country) values ('Belgium');
INSERT INTO countries (country) values ('Belize');
INSERT INTO countries (country) values ('Benin');
INSERT INTO countries (country) values ('Bermuda');
INSERT INTO countries (country) values ('Bhutan');
INSERT INTO countries (country) values ('Bolivia');
INSERT INTO countries (country) values ('Bosnia and Herzegovina');
INSERT INTO countries (country) values ('Botswana');
INSERT INTO countries (country) values ('Brazil');
INSERT INTO countries (country) values ('British Virgin Islands');
INSERT INTO countries (country) values ('Brunei');
INSERT INTO countries (country) values ('Bulgaria');
INSERT INTO countries (country) values ('Burkina Faso');
INSERT INTO countries (country) values ('Burma');
INSERT INTO countries (country) values ('Burundi');
INSERT INTO countries (country) values ('Cambodia');
INSERT INTO countries (country) values ('Cameroon');
INSERT INTO countries (country) values ('Canada');
INSERT INTO countries (country) values ('Cape Verde');
INSERT INTO countries (country) values ('Central African Republic');
INSERT INTO countries (country) values ('Chad');
INSERT INTO countries (country) values ('Chile');
INSERT INTO countries (country) values ('China');
INSERT INTO countries (country) values ('Colombia');
INSERT INTO countries (country) values ('Comoros');
INSERT INTO countries (country) values ('Congo');
INSERT INTO countries (country) values ('Congo');
INSERT INTO countries (country) values ('Cook Islands');
INSERT INTO countries (country) values ('Costa Rica');
INSERT INTO countries (country) values ('Cote d''Ivoire');
INSERT INTO countries (country) values ('Croatia');
INSERT INTO countries (country) values ('Cuba');
INSERT INTO countries (country) values ('Cyprus');
INSERT INTO countries (country) values ('Czech Republic');
INSERT INTO countries (country) values ('Denmark');
INSERT INTO countries (country) values ('Djibouti');
INSERT INTO countries (country) values ('Dominica');
INSERT INTO countries (country) values ('Dominican Republic');
INSERT INTO countries (country) values ('Ecuador');
INSERT INTO countries (country) values ('Egypt');
INSERT INTO countries (country) values ('El Salvador');
INSERT INTO countries (country) values ('Equatorial Guinea');
INSERT INTO countries (country) values ('Eritrea');
INSERT INTO countries (country) values ('Estonia');
INSERT INTO countries (country) values ('Ethiopia');
INSERT INTO countries (country) values ('Falkland Islands');
INSERT INTO countries (country) values ('Fiji');
INSERT INTO countries (country) values ('Finland');
INSERT INTO countries (country) values ('France');
INSERT INTO countries (country) values ('French Guiana');
INSERT INTO countries (country) values ('French Polynesia');
INSERT INTO countries (country) values ('Gabon');
INSERT INTO countries (country) values ('The Gambia');
INSERT INTO countries (country) values ('Gaza Strip and West Bank');
INSERT INTO countries (country) values ('Georgia');
INSERT INTO countries (country) values ('Germany');
INSERT INTO countries (country) values ('Ghana');
INSERT INTO countries (country) values ('Gibraltar');
INSERT INTO countries (country) values ('Greece');
INSERT INTO countries (country) values ('Greenland');
INSERT INTO countries (country) values ('Grenada');
INSERT INTO countries (country) values ('Guadeloupe');
INSERT INTO countries (country) values ('Guam');
INSERT INTO countries (country) values ('Guatemala');
INSERT INTO countries (country) values ('Guinea');
INSERT INTO countries (country) values ('Guinea-Bissau');
INSERT INTO countries (country) values ('Guyana');
INSERT INTO countries (country) values ('Haiti');
INSERT INTO countries (country) values ('The Holy See');
INSERT INTO countries (country) values ('Honduras');
INSERT INTO countries (country) values ('Hong Kong');
INSERT INTO countries (country) values ('Hungary');
INSERT INTO countries (country) values ('Iceland');
INSERT INTO countries (country) values ('India');
INSERT INTO countries (country) values ('Indonesia');
INSERT INTO countries (country) values ('Iran');
INSERT INTO countries (country) values ('Iraq');
INSERT INTO countries (country) values ('Ireland');
INSERT INTO countries (country) values ('Israel');
INSERT INTO countries (country) values ('Italy');
INSERT INTO countries (country) values ('Ivory Coast');
INSERT INTO countries (country) values ('Jamaica');
INSERT INTO countries (country) values ('Japan');
INSERT INTO countries (country) values ('Jordan');
INSERT INTO countries (country) values ('Kazakhstan');
INSERT INTO countries (country) values ('Kenya');
INSERT INTO countries (country) values ('Kiribati');
INSERT INTO countries (country) values ('Kuwait');
INSERT INTO countries (country) values ('Kyrgyzstan');
INSERT INTO countries (country) values ('Laos');
INSERT INTO countries (country) values ('Latvia');
INSERT INTO countries (country) values ('Lebanon');
INSERT INTO countries (country) values ('Lesotho');
INSERT INTO countries (country) values ('Liberia');
INSERT INTO countries (country) values ('Libya');
INSERT INTO countries (country) values ('Liechtenstein');
INSERT INTO countries (country) values ('Lithuania');
INSERT INTO countries (country) values ('Luxembourg');
INSERT INTO countries (country) values ('Macau');
INSERT INTO countries (country) values ('Macedonia');
INSERT INTO countries (country) values ('Madagascar');
INSERT INTO countries (country) values ('Malawi');
INSERT INTO countries (country) values ('Malaysia');
INSERT INTO countries (country) values ('Maldives');
INSERT INTO countries (country) values ('Mali');
INSERT INTO countries (country) values ('Malta');
INSERT INTO countries (country) values ('Marshall Islands');
INSERT INTO countries (country) values ('Martinique');
INSERT INTO countries (country) values ('Mauritania');
INSERT INTO countries (country) values ('Mauritius');
INSERT INTO countries (country) values ('Mayotte');
INSERT INTO countries (country) values ('Mexico');
INSERT INTO countries (country) values ('Federated States of Micronesia');
INSERT INTO countries (country) values ('Moldova');
INSERT INTO countries (country) values ('Monaco');
INSERT INTO countries (country) values ('Mongolia');
INSERT INTO countries (country) values ('Montserrat');
INSERT INTO countries (country) values ('Morocco');
INSERT INTO countries (country) values ('Mozambique');
INSERT INTO countries (country) values ('Namibia');
INSERT INTO countries (country) values ('Nauru');
INSERT INTO countries (country) values ('Nepal');
INSERT INTO countries (country) values ('Netherlands');
INSERT INTO countries (country) values ('Netherlands Antilles');
INSERT INTO countries (country) values ('New Caledonia');
INSERT INTO countries (country) values ('New Zealand');
INSERT INTO countries (country) values ('Nicaragua');
INSERT INTO countries (country) values ('Niger');
INSERT INTO countries (country) values ('Nigeria');
INSERT INTO countries (country) values ('North Korea');
INSERT INTO countries (country) values ('Northern Mariana Islands');
INSERT INTO countries (country) values ('Norway');
INSERT INTO countries (country) values ('Oman');
INSERT INTO countries (country) values ('Pakistan');
INSERT INTO countries (country) values ('Palau');
INSERT INTO countries (country) values ('Panama');
INSERT INTO countries (country) values ('Papua New Guinea');
INSERT INTO countries (country) values ('Paraguay');
INSERT INTO countries (country) values ('Peru');
INSERT INTO countries (country) values ('Philippines');
INSERT INTO countries (country) values ('Pitcairn Islands');
INSERT INTO countries (country) values ('Poland');
INSERT INTO countries (country) values ('Portugal');
INSERT INTO countries (country) values ('Puerto Rico');
INSERT INTO countries (country) values ('Qatar');
INSERT INTO countries (country) values ('Reunion');
INSERT INTO countries (country) values ('Romania');
INSERT INTO countries (country) values ('Russia');
INSERT INTO countries (country) values ('Rwanda');
INSERT INTO countries (country) values ('Saint Kitts and Nevis');
INSERT INTO countries (country) values ('Saint Lucia');
INSERT INTO countries (country) values ('Saint Pierre and Miquelon');
INSERT INTO countries (country) values ('Saint Vincent and the Grenadines');
INSERT INTO countries (country) values ('Samoa');
INSERT INTO countries (country) values ('San Marino');
INSERT INTO countries (country) values ('Sao Tome and Principe');
INSERT INTO countries (country) values ('Saudi Arabia');
INSERT INTO countries (country) values ('Senegal');
INSERT INTO countries (country) values ('Serbia and Montenegro');
INSERT INTO countries (country) values ('Seychelles');
INSERT INTO countries (country) values ('Sierra Leone');
INSERT INTO countries (country) values ('Singapore');
INSERT INTO countries (country) values ('Slovakia');
INSERT INTO countries (country) values ('Slovenia');
INSERT INTO countries (country) values ('Solomon Islands');
INSERT INTO countries (country) values ('Somalia');
INSERT INTO countries (country) values ('South Africa');
INSERT INTO countries (country) values ('South Korea');
INSERT INTO countries (country) values ('Spain');
INSERT INTO countries (country) values ('Sri Lanka');
INSERT INTO countries (country) values ('Sudan');
INSERT INTO countries (country) values ('Suriname');
INSERT INTO countries (country) values ('Swaziland');
INSERT INTO countries (country) values ('Sweden');
INSERT INTO countries (country) values ('Switzerland');
INSERT INTO countries (country) values ('Syria');
INSERT INTO countries (country) values ('Taiwan');
INSERT INTO countries (country) values ('Tajikistan');
INSERT INTO countries (country) values ('Tanzania');
INSERT INTO countries (country) values ('Thailand');
INSERT INTO countries (country) values ('Togo');
INSERT INTO countries (country) values ('Tonga');
INSERT INTO countries (country) values ('Trinidad and Tobago');
INSERT INTO countries (country) values ('Tunisia');
INSERT INTO countries (country) values ('Turkey');
INSERT INTO countries (country) values ('Turkmenistan');
INSERT INTO countries (country) values ('Turks and Caicos Islands');
INSERT INTO countries (country) values ('Tuvalu');
INSERT INTO countries (country) values ('Uganda');
INSERT INTO countries (country) values ('Ukraine');
INSERT INTO countries (country) values ('United Arab Emirates');
INSERT INTO countries (country) values ('United Kingdom');
INSERT INTO countries (country) values ('United States');
INSERT INTO countries (country) values ('United States Virgin Islands');
INSERT INTO countries (country) values ('Uruguay');
INSERT INTO countries (country) values ('Uzbekistan');
INSERT INTO countries (country) values ('Vanuatu');
INSERT INTO countries (country) values ('Venezuela');
INSERT INTO countries (country) values ('Vietnam');
INSERT INTO countries (country) values ('West Bank and Gaza Strip');
INSERT INTO countries (country) values ('Western Sahara');
INSERT INTO countries (country) values ('Yemen');
INSERT INTO countries (country) values ('Yugoslavia');
INSERT INTO countries (country) values ('Zaire');
INSERT INTO countries (country) values ('Zambia');
INSERT INTO countries (country) values ('Zimbabwe');
