INSERT INTO specializations (specialization) values ('Artificial Intelligence');
INSERT INTO specializations (specialization) values ('Cognitive Science');
INSERT INTO specializations (specialization) values ('Computer Engineering');
INSERT INTO specializations (specialization) values ('Computer Information Systems');
INSERT INTO specializations (specialization) values ('Computer Graphics');
INSERT INTO specializations (specialization) values ('Computer Programming');
INSERT INTO specializations (specialization) values ('Computer Networks');
INSERT INTO specializations (specialization) values ('Computer Science Theory');
INSERT INTO specializations (specialization) values ('Computer Servicing Technology');
INSERT INTO specializations (specialization) values ('Computer System Architecture');
INSERT INTO specializations (specialization) values ('Data Processing');
INSERT INTO specializations (specialization) values ('Database Systems');
INSERT INTO specializations (specialization) values ('Information Science');
INSERT INTO specializations (specialization) values ('Knowledge Engineering/Expert Systems');
INSERT INTO specializations (specialization) values ('Management Information Systems');
INSERT INTO specializations (specialization) values ('Neural Networks');
INSERT INTO specializations (specialization) values ('Robotics');
INSERT INTO specializations (specialization) values ('Software Engineering');
INSERT INTO specializations (specialization) values ('Systems Analysis');
INSERT INTO specializations (specialization) values ('Telecommunications Engineering');
INSERT INTO specializations (specialization) values ('Other');
